baseURL = "https://isahil.me"
languageCode = "en-us"
title = "Sahil M"
theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = true
googleAnalytics = 'G-FNK6G1Q9P7'
canonifyURLs=true

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "RSS"]

  
[minify]
disableXML = true
minifyOutput = true

[markup.goldmark.renderer]
unsafe = true

[[Menus.main]]
identifier = "blog"
name = "Blog"
title = "Blog posts"
url = "/blogs"
weight = 1

# [[Menus.main]]
# identifier = "gallery"
# name = "Gallery"
# title = "Blog posts"
# url = "/gallery"
# weight = 2

[params]
title = "Sahil"
description = "Hi there, My name is Sahil Mangotra. I am a software developer and this is my site."
favicon = "/favicon.ico"
useBootstrapCDN = false
mathjax = true
animate = true
math = true

[params.font]
fontSize = "1rem"
fontWeight = 400
lineHeight = 1.5
textAlign = "left"

[params.navbar]
align = "ms-auto"
brandName = "Home"
disableSearch = false
enableSeparator = false

[params.navbar.stickyNavBar]
enable = true
showOnScrollUp = true

[params.navbar.menus]
disableAbout = false
disableExperience = false
disableEducation = false
disableProjects = false
disableAchievements = false
disableContact = false

[params.hero]
enable = true
intro = "Hi, my name is"
title = "Sahil Mangotra."
subtitle = "Software Engineer → AI"
content = "I'm a passionate web app developer with a strong focus on modern web technologies to create websites that look great, feel intuitive, and perform flawlessly. Previously a software engineer, I'm now pursuing a master's in Computer Science with a concentration in AI."
image = "/sahil.jpeg"

[params.hero.bottomImage]
enable = true

[params.hero.button]
enable = true
name = "Resume"
url = "https://docs.google.com/document/d/1SUbgJZcg_6top9cRryehffSKGWhR2sKzFaBWZ_ZhGwQ/edit?usp=sharing"
download = true
newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/Sahil624/"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-x-twitter"
url = "https://x.com/Sahilmangotra1"

# [[params.hero.socialLinks.customIcons]]
# icon = "/fav.png"
# url = "https://example.com"

[params.about]
enable = true
title = "About Me"
image = "/me.jpeg"
content = """
I'm a seasoned software developer with a strong foundation in computer science and mathematics, passionate about web development and innovative tech solutions. I previously served as a Lead Software Engineer at uTrade Solutions in Mohali, India, where I led projects in algorithmic trading, optimized database operations, and guided teams in microservice architecture transitions to enhance trading performance and system efficiency.

Currently, I'm advancing my expertise through a master’s in Computer Science with a concentration in AI. My research focuses on integrating AI into adaptive learning platforms, expanding my skills at the cutting edge of technology. Whether I'm mentoring junior developers, optimizing tech solutions, or exploring new AI applications, I bring a comprehensive skill set and a collaborative spirit to every endeavor.
."""

[params.about.skills]
enable = true
title = "Here are a few technologies I've been working with recently:"
items = [
  "Golang",
  "Django",
  "Python",
  "Postgres SQL",
  "Kafka",
  "Angular",
  "Docker",
  "PyTorch",
  "FastAI"
]

[params.experience]
enable = true

[[params.experience.items]]
job = "Graduate Research Assistant"
company = "Kennesaw State University"
companyUrl = "https://www.kennesaw.edu/ccse/index.php"
date = "August 2024 - Present"
content = """
- Collaborated with Dr. Abhishek Prakash to develop an AI-driven Quantum Computing Course Generator, personalizing content based on student learning patterns and proficiency.
- Designed adaptive algorithms integrating quantum computing and AI to create a dynamic educational platform. 
- Conducted research and data analysis to optimize tool performance for accurate, personalized learning experiences.
"""

[params.experience.items.featuredLink]
enable = true
name = "Kennesaw State University"
url = "https://www.kennesaw.edu/ccse/index.php"


[[params.experience.items]]
job = "Lead Software Engineer"
company = "uTrade Solutions"
companyUrl = "https://utradesolutions.com"
date = "September 2023 - July 2024"
content = """
- Led architectural and management initiatives to design a new algo-based trading platform, which was well-received
by management and business partners
- Fostered collaboration with the Exchange end adapter teams, enhancing the flow of market data for real-time insights
- Provided mentoring and training to new hires and interns, enhancing their trading expertise and technical skills
- Made strategic decisions to innovate trading platforms, which resulted in enhanced system performance
- Planned the migration of legacy monolithic architecture to micro-service architecture, adding new technologies like
Golang and Kafka. This resulted in a 15% enhancement in the turnaround time for development and deployment
"""

[params.experience.items.featuredLink]
enable = true
name = "uTrade Solutions"
url = "https://utradesolutions.com"


[[params.experience.items]]
job = "Senior Software Engineer"
company = "uTrade Solutions"
companyUrl = "https://utradesolutions.com"
date = "September 2020 - October 2023"
content = """
- Developed a user-driven platform for creating trading algorithms, significantly improving user engagement
- Worked with the Exchange end adapter teams to optimise market data flow, improving data reception speed by 30%
using new compression techniques and optimising market data packets
- Executed optimal SQL database operations, effectively handling millions of rows of market data. I designed and
implemented in-house sharding and buffering of this data to combine multiple rows into one on the fly
"""

[params.experience.items.featuredLink]
enable = true
name = "uTrade Solutions"
url = "https://utradesolutions.com"

[[params.experience.items]]
job = "Software Developer"
company = "uTrade Solutions"
companyUrl = "https://utradesolutions.com"
date = "June 2019 - September 2020"
content = """
- Developed and implemented a simplified version of the trading platform that features a 30% smaller build size and
was developed with low-end devices in mind, thus broadening the market reach to new clients
- Developed a mobile application using Ionic that facilitates trading on the go for clients
- Designed a REST-based server, which enabled multiple apps to connect to the backend as a Platform as a Service
- Contributed to a successful UI redesign, receiving praise from senior management
"""

[params.experience.items.featuredLink]
enable = true
name = "uTrade Solutions"
url = "https://utradesolutions.com"

[[params.experience.items]]
job = "Full-stack Developer Intern"
company = "uTrade Solutions"
companyUrl = "https://utradesolutions.com"
date = "June 2018 - May 2019"
content = """
- Collaborated with the Product Team to establish the business specifications within the Fintech domain
- Solved complex technical issues using modern mobile and web technologies
- Presented technical solutions to senior executives, facilitating informed decision-making
"""

[params.experience.items.featuredLink]
enable = true
name = "uTrade Solutions"
url = "https://utradesolutions.com"

[params.education]
enable = true
index = false


[[params.education.items]]
title = "Master of Science in Computer Science (AI Concentration)"
date = "Expected Graduation: 2026"
# GPA = "3.83 out of 4.0"
content = """
Engaged in advanced AI and ML coursework, applying theory to practical problems, and collaborated on a capstone project to design an AI-based recommendation system that improved user engagement by 30% in simulations.
"""

[params.education.items.school]
name = "Kennesaw State University"
url = "https://www.kennesaw.edu/ccse/index.php"


[[params.education.items]]
title = "Bachelor of Engineering in Computer Science"
date = "2015 - 2019"
GPA = "3.83 out of 4.0"
content = """
I was part of the University Coding Academy. I passed a rigorous coding exam and interview, and was selected among a few students from the entire university. In uCA, we were taught complex subjects like advanced algorithms and advanced operating systems by external faculty associated with industry leaders like Infosys and Google.

Extracurricular Activities:
  - Participated in various coding competitions and hackathons.
"""

[params.education.items.school]
name = "Chitkara University"
url = "https://www.chitkara.edu.in"

[[params.education.items]]
title = "High School"
GPA = "8.2 out of 10"

[params.education.items.school]
name = "Lawrance Public Senior Secondary School"
url = "https://www.lpsmohali.com"

[params.achievements]
enable = false

[[params.achievements.items]]
title = "Google kickstart runner"
content = "I solved all problems with optimal solution."
url = "https://example.com"
image = "/images/achievment.jpg"

[params.projects]
enable = true


[[params.projects.items]]
title = "Day Canvas"
content = """
'DayCanvas' converts daily journal entries into animated story sequences. Users write about their day, and our platform transforms their experiences into fantasy-style visual narratives, creating a parallel universe that reflects their emotional journey in a creative and engaging way.
"""
image = "/daycanvas.jpeg"
badges = ["AI", "Claude", "Imagen3", "Gemini", "Django"]

[params.projects.items.featured]
name = "Demo"
link = "https://www.youtube.com/watch?v=0QzIm0jzxBM"

[[params.projects.items.links]]
icon = "fab fa-github"
url = "https://github.com/Sahil624/DayCanvas"

[[params.projects.items]]
title = "Quick Notes"
content = """
"Quick Notes" is an Angular-based application designed for creating and managing notes. It uses Firebase as the backend for storage and authentication. The project is set up with GitHub Actions to automate the deployment process, allowing the application to be seamlessly deployed on GitHub Pages.
"""
image = "/quick_note.png"
badges = ["Angular", "Firebase"]

[params.projects.items.featured]
name = "App"
link = "https://quicknote.isahil.me/"

[[params.projects.items.links]]
icon = "fab fa-github"
url = "https://github.com/Sahil624/quick-note"

[[params.projects.items]]
title = "Chatting and Media Sharing Application Backend"
content = """
Developed a comprehensive chatting system with capabilities for one-to-one chat, group chat, media sharing, and audio/video calls. Designed a robust software architecture that handled 10,000 active users in production. Features include channel creation, subscription management, and the ability to like, comment, and share videos and news.
"""
image = "https://yt3.googleusercontent.com/ytc/AIdro_ls60_itXZv6S8fpzhGHU7SIMBaf9cHML-MLYBdyAF38Q=s160-c-k-c0x00ffffff-no-rj"
badges = ["Python", "Django", "WebRTC"]

[[params.projects.items]]
title = "Network Sniffer"
content = """
Developed a CLI application in Python that sniffs network traffic on a system, analyzing different types of packets (ICMP, IPv4, IPv6). The application logs the source and destination addresses of packets, providing detailed traffic analysis.
"""
image = "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png"
badges = ["Python", "CLI"]

[[params.projects.items.links]]
icon = "fab fa-github"
url = "https://github.com/Sahil624/python-network-sniffer"

[params.contact]
enable = true
content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
btnName = "Mail me"
btnLink = "mailto:hi@isahil.me"

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/Sahil624/"
linkedin = "https://www.linkedin.com/in/sahil624/"
twitter = "https://x.com/Sahilmangotra1"
instagram = "https://www.instagram.com/1997sahil/"

[params.listPages]
disableFeaturedImage = false

[params.singlePages]
socialShare = true

[params.singlePages.readTime]
enable = true
content = "min read"

[params.singlePages.scrollprogress]
enable = true

[params.singlePages.tags]
openInNewTab = true

[params.terms]
read = "Read"
toc = "Table Of Contents"
copyright = "All rights reserved"
pageNotFound = "Page not found"
emailText = "Check out this site"

[params.datesFormat]
article = "Jan 2, 2006"
articleList = "Jan 2, 2006"
articleRecent = "Jan 2, 2006"
