baseURL = "https://isahil.me"
languageCode = "en-us"
title = "Sahil M"
theme = "hugo-profile"
Paginate = 3
enableRobotsTXT = true
googleAnalytics = 'G-FNK6G1Q9P7'

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML", "RSS"]

[markup.goldmark.renderer]
unsafe = true

# [[Menus.main]]
# identifier = "blog"
# name = "Blog"
# title = "Blog posts"
# url = "/blogs"
# weight = 1

# [[Menus.main]]
# identifier = "gallery"
# name = "Gallery"
# title = "Blog posts"
# url = "/gallery"
# weight = 2

[params]
title = "Sahil"
description = "Hi there, My name is Sahil Mangotra. I am a software developer and this is my site."
favicon = "/favicon.ico"
useBootstrapCDN = false
mathjax = false
animate = true

[params.font]
fontSize = "1rem"
fontWeight = 400
lineHeight = 1.5
textAlign = "left"

[params.navbar]
align = "ms-auto"
brandName = "Home"
disableSearch = false
enableSeparator = false

[params.navbar.stickyNavBar]
enable = true
showOnScrollUp = true

[params.navbar.menus]
disableAbout = false
disableExperience = false
disableEducation = false
disableProjects = false
disableAchievements = false
disableContact = false

[params.hero]
enable = true
intro = "Hi, my name is"
title = "Sahil Mangotra."
subtitle = "I build things for the web"
content = "A passionate web app developer. I tend to make use of modern web technologies to build websites that looks great, feels fantastic, and functions correctly."
image = "/images/sahil.jpeg"

[params.hero.bottomImage]
enable = true

[params.hero.button]
enable = true
name = "Resume"
url = "https://drive.google.com/file/d/1ZJhGAzUhp1YdrUzpWqoUrAzwHlmhhWVy/view"
download = true
newPage = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/Sahil624/"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-x-twitter"
url = "https://x.com/Sahilmangotra1"

# [[params.hero.socialLinks.customIcons]]
# icon = "/fav.png"
# url = "https://example.com"

[params.about]
enable = true
title = "About Me"
image = "/images/me.jpeg"
content = """

Here’s an enhanced version of your bio that highlights your expertise and passion in a more engaging way:

I am a seasoned software developer with a deep passion for web development and a solid foundation in computer science and mathematics. I thrive at the intersection of technology and art, constantly seeking innovative ways to blend these fields. Currently, I am a Lead Software Engineer at [uTrade Solutions.](https://utradesolutions.com/) in Mohali, Punjab, India.

At uTrade Solutions, I lead the development of cutting-edge projects focused on automating stock market trading using sophisticated algorithms. My work involves designing and implementing robust trading platforms that empower users to trade efficiently and effectively.

With a keen eye for detail and a dedication to creating seamless user experiences, I continually push the boundaries of what’s possible in web development. Whether mentoring junior developers, optimizing database operations, or enhancing web security, I bring a comprehensive skill set and a collaborative spirit to every project.
."""

[params.about.skills]
enable = true
title = "Here are a few technologies I've been working with recently:"
items = [
  "Golang",
  "Django",
  "Python",
  "FastAPI",
  "Postgres SQL",
  "Kafka",
  "Angular",
]

[params.experience]
enable = true

[[params.experience.items]]
job = "Lead Software Engineer"
company = "uTrade Solutions"
companyUrl = "https://utradesolutions.com"
date = "September 2023 - Present"
content = """
Leading the development and optimization of market data flow systems, enhancing real-time trading platforms, and mentoring new hires to ensure high standards in software development.
"""

[params.experience.items.featuredLink]
enable = true
name = "uTrade Solutions"
url = "https://utradesolutions.com"

[[params.experience.items]]
job = "Senior Software Engineer"
company = "uTrade Solutions"
companyUrl = "https://utradesolutions.com"
date = "September 2020 - October 2023"
content = """
Developed user-driven trading algorithm platforms, managed complex projects independently, and optimized SQL databases for high-volume data, ensuring robust web application security.
"""

[params.experience.items.featuredLink]
enable = true
name = "uTrade Solutions"
url = "https://utradesolutions.com"

[[params.experience.items]]
job = "Full-stack Developer"
company = "uTrade Solutions"
companyUrl = "https://utradesolutions.com"
date = "June 2019 - September 2020"
content = """
Created a lite trading platform and mobile app for new users, developed REST-based backend for multi-app connectivity, and led UI revamp projects, earning recognition from senior management.
"""

[params.experience.items.featuredLink]
enable = true
name = "uTrade Solutions"
url = "https://utradesolutions.com"

[[params.experience.items]]
job = "Full-stack Developer Intern"
company = "uTrade Solutions"
companyUrl = "https://utradesolutions.com"
date = "June 2018 - May 2019"
content = """
Collaborated with the Product Team on fintech requirements, coded software changes per design specifications, and presented solutions to senior executives, gaining hands-on experience in network analytics tools.
"""

[params.experience.items.featuredLink]
enable = true
name = "uTrade Solutions"
url = "https://utradesolutions.com"

[params.education]
enable = true
index = false

[[params.education.items]]
title = "Bachelor of Engineering in Computer Science"
date = "2015 - 2019"
GPA = "3.83 out of 4.0"
content = """
I was part of the University Coding Academy. I passed a rigorous coding exam and interview, and was selected among a few students from the entire university. In uCA, we were taught complex subjects like advanced algorithms and advanced operating systems by external faculty associated with industry leaders like Infosys and Google.

Extracurricular Activities:
  - Participated in various coding competitions and hackathons.
"""

[params.education.items.school]
name = "Chitkara University"
url = "https://www.chitkara.edu.in"

[[params.education.items]]
title = "High School"
GPA = "8.2 out of 10"

[params.education.items.school]
name = "Lawrance Public Senior Secondary School"
url = "https://www.lpsmohali.com"

[params.achievements]
enable = false

[[params.achievements.items]]
title = "Google kickstart runner"
content = "I solved all problems with optimal solution."
url = "https://example.com"
image = "/images/achievment.jpg"

[[params.achievements.items]]
title = "Facebook Hackathon Winner"
content = "Developed a product using Artificial Intelligence."
image = "/images/achievment.jpg"

[[params.achievements.items]]
title = "Hugo Profile"
content = "Developed a theme and getting 1K+ downloads per month."
url = "https://github.com/gurusabarish/hugo-profile"
image = "/images/achievment.jpg"

[[params.achievements.items]]
title = "Microsoft Imagine Runner"
content = "We are developed a product which can help others."

[[params.achievements.items]]
title = "Google Summer of Code"
content = "Contributed to a open source project."
url = "https://example.com"

[params.projects]
enable = true

[[params.projects.items]]
title = "Chatting and Media Sharing Application Backend"
content = """
Developed a comprehensive chatting system with capabilities for one-to-one chat, group chat, media sharing, and audio/video calls. Designed a robust software architecture that handled 10,000 active users in production. Features include channel creation, subscription management, and the ability to like, comment, and share videos and news.
"""
image = "https://yt3.googleusercontent.com/ytc/AIdro_ls60_itXZv6S8fpzhGHU7SIMBaf9cHML-MLYBdyAF38Q=s160-c-k-c0x00ffffff-no-rj"
badges = ["Python", "Django", "WebRTC"]

# [params.projects.items.featured]
# name = "Gizmoh Communicator"
# link = "https://gizmohcommunicator.com/"

# [[params.projects.items.links]]
# icon = "fab fa-github"
# url = "https://github.com/Sahil624/chatting-media-sharing-backend"

[[params.projects.items]]
title = "Network Sniffer"
content = """
Developed a CLI application in Python that sniffs network traffic on a system, analyzing different types of packets (ICMP, IPv4, IPv6). The application logs the source and destination addresses of packets, providing detailed traffic analysis.
"""
image = "https://github.githubassets.com/assets/GitHub-Mark-ea2971cee799.png"
badges = ["Python", "CLI"]

[[params.projects.items.links]]
icon = "fab fa-github"
url = "https://github.com/Sahil624/python-network-sniffer"

[params.contact]
enable = true
content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
btnName = "Mail me"
btnLink = "mailto:gurusabarisha@gmail.com"

[params.footer.recentPosts]
path = "blogs"
count = 3
title = "Recent Posts"
enable = true
disableFeaturedImage = false

[params.footer.socialNetworks]
github = "https://github.com/Sahil624/"
linkedin = "https://www.linkedin.com/in/sahil624/"
twitter = "https://x.com/Sahilmangotra1"
instagram = "https://www.instagram.com/1997sahil/"

[params.listPages]
disableFeaturedImage = false

[params.singlePages]
socialShare = true

[params.singlePages.readTime]
enable = true
content = "min read"

[params.singlePages.scrollprogress]
enable = true

[params.singlePages.tags]
openInNewTab = true

[params.terms]
read = "Read"
toc = "Table Of Contents"
copyright = "All rights reserved"
pageNotFound = "Page not found"
emailText = "Check out this site"

[params.datesFormat]
article = "Jan 2, 2006"
articleList = "Jan 2, 2006"
articleRecent = "Jan 2, 2006"
